services:
  - type: web
    name: instagram-follower-analyzer-api
    env: docker
    rootDir: .
    buildCommand: docker build -t instagram-follower-analyzer .
    startCommand: docker run -p 5000:5000 instagram-follower-analyzer
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: persistent-disk
      mountPath: /app
      sizeGB: 2

  - type: static
    name: instagram-follower-analyzer-frontend
    rootDir: frontend
    buildCommand: |
      chmod +x build.sh
      ./build.sh
    publishDir: build
    envVars:
      - key: REACT_APP_API_URL
        sync: false # Will be set manually
      - key: CI
        value: false
      - key: NODE_ENV
        value: production
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
